### PR TITLE
Handle DataChannelAck as Client

### PR DESCRIPTION
**Pull request by backkem**
#### Description
Handle DataChannelAck as Client

#### Reference issue
Relates to pions/webrtc#167

### CODE REVIEW

**Comment by backkem** [comment]
Note that I skipped this part of the spec for now:
> However, before the DATA_CHANNEL_ACK
   message or any other message has been received on a Data Channel, all
   other messages containing user data and belonging to this Data
   Channel MUST be sent ordered, no matter whether the Data Channel is
   ordered or not.

**Comment by enobufs** [comment]
@backkem I noticed that requirement in the earlier work and implemented the following code in [stream.go](https://github.com/pions/sctp/blob/5179f77cf05608bea6fd33c66a2820662858b089/stream.go#L178-L181):
```go
	// From draft-ietf-rtcweb-data-protocol-09, section 6:
	//   All Data Channel Establishment Protocol messages MUST be sent using
	//   ordered delivery and reliable transmission.
	unordered := ppi != PayloadTypeWebRTCDCEP && s.unordered
```
Is that what you meant?

**Comment by backkem** [comment]
Two thoughts:
- The spec says `all other messages` should be send reliable & ordered before the ack is received. This only seems to relate to the DCEP messages.
- This isn't the best separation of concerns. It would be better if all of the data channel spec lives in this package.

**Comment by enobufs** [comment]
Confirmed your point, in section 6:
```
However, before the DATA_CHANNEL_ACK
   message or any other message has been received on a Data Channel, all
   other messages containing user data and belonging to this Data
   Channel MUST be sent ordered, no matter whether the Data Channel is
   ordered or not.
```
SCTP has no knowledge of the receipt of ACK.  I guess, DCEP layer needs to tell the stream layer (in SCTP) some whether to ignore unordered option... (I guess this what you mean by "This isn't the best separation of concerns."..., and I agree.)

**Comment by backkem** [comment]
What we could do would be to call `SetReliabilityParams` once the ack has heen received instead of at the creation of the DataChannel. That would be decent separation of concerns.

**Comment by enobufs** [comment]
The changes look good to me.  (I create a new issue #10 to follow up on disabling 'unordered' option until the ack is received.)

**Comment by backkem** [comment]
Closing since I think it's a step in the wrong direction. We should just solve #10 instead.

**Pull request closed without merging**
